---
title: "STAT230 Final Project"
author: "Noah, Alex, Lucas"
date: "2024-03-04"
output:
  pdf_document: default
  html_document: default
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mosaic)
library(ggformula)
library(car)
library(GGally)
library(broom)
library(ggeffects)
library(effects)
library(tidyr)
library(ggplot2)
library(rms)

final_data <- final_data %>%
  mutate(pts_allowed_log = log(pts_allowed))
```

3 POINT ATTEMPTED UNIVARIATE PLOT: - RIGHT SKEW

```{r}
gf_boxplot(~FG3A, data=final_data) + 
  theme_bw()
gf_histogram(~FG3A, data=final_data) + 
  theme_bw()
```

```{r}
gf_jitter(FG3A~SEASON, data=final_data) %>% gf_lm() + 
  labs(x="Season", y="3-point Field Goals Attempted", title="Number of 3-Point field goals attempted in-game over different seasons") + theme_bw()
```

```{r}
gf_jitter(FG3A~pts_allowed, data=final_data) %>% gf_lm()+ theme_bw()
```

```{r}
gf_jitter(fg3_pct~FG3A, data=final_data) %>% gf_lm()+ theme_bw()
```

MODEL:

```{r}
nba_glm <- glm(win ~ FG3A  + log(pts_allowed) + FTA  + OREB + DREB + TO + SEASON + FG3A:SEASON, data = final_data, family = "binomial")
summary(nba_glm)
1 - pchisq(53647, 53095) #INADEQUACY
```

```{r}
nba_glm2 <- glm(win ~ FG3A + fg3_pct  + pts_allowed_log + FTA  + reb + TO + SEASON + FG3A:SEASON + log(pts_allowed):SEASON, data = final_data, family = "binomial")
summary(nba_glm2)
1 - pchisq(45192, 53094) #ADEQUATE
```

MULTI COLLINEARITY:

```{r}
final_data |> 
  ggpairs(columns = c("win", "FG3A", "fg3_pct", "pts_allowed", "FTA", "reb", "TO", "SEASON"))
```

```{r}
vif(nba_glm2)
```

No evidence of significant multicollinearity with non-interaction terms.

OUTLIERS:

```{r}
plot(rstandard(nba_glm2), main="Standardized Residuals", ylab="Standardized Residuals", xlab="Index")
plot(hatvalues(nba_glm2), main="Hat Values", ylab="Standardized Residuals", xlab="Index")
plot(cooks.distance(nba_glm2), main="Cooks D", ylab="Standardized Residuals", xlab="Index") 
cooks_d <- cooks.distance(nba_glm2)
influential_obs <- which(cooks_d > 0.0015)
print(influential_obs) # gameid = 10600015, 20700065
```

PLOTS: win v 3PA:

```{r}
lm_preds <- ggpredict(nba_glm2, terms = c("FG3A"))
plot(lm_preds, show_data = TRUE) + 
  labs(title="Predicted Probability of winning based on 3 points shot", x="3FGA", y="Predicted probability of winning")
```

win v pts allowed:

```{r}
lm_preds <- ggpredict(nba_glm2, terms = c("pts_allowed"))
plot(lm_preds, show_data = TRUE) + 
  labs(title="Predicted Probability of winning based on pts_allowed", x="pts_allowed", y="Predicted probability of winning")
```

win v free throws attempted

```{r}
lm_preds <- ggpredict(nba_glm2, terms = c("FG3A", "fg3_pct"))
plot(lm_preds, show_data = TRUE) + 
labs(title="Predicted Probability of winning based on 3FGA and Percentage", x="FG3A", y="Predicted probability of winning")
```

win v OREB

```{r}
lm_preds <- ggpredict(nba_glm, terms = c("OREB"))
plot(lm_preds, show_data = TRUE) + 
  labs(title="Predicted Probability of winning based on OREB", x="OREB", y="Predicted probability of winning")
```

win v DREB

```{r}
lm_preds <- ggpredict(nba_glm, terms = c("DREB"))
plot(lm_preds, show_data = TRUE) + 
  labs(title="Predicted Probability of winning based on DREB", x="DREB", y="Predicted probability of winning")
#>>>>>>> 0bf3a88872e7f0a7cb677c6ccd4cb5f62af21253
```

win v TO

```{r}
lm_preds <- ggpredict(nba_glm, terms = c("TO"))
plot(lm_preds, show_data = TRUE) + 
  labs(title="Predicted Probability of winning based on TO", x="TO", y="Predicted probability of winning")
```

```{r}
lm_preds <- ggpredict(nba_glm2, terms = c("FG3A", "pts_allowed"))
plot(lm_preds, show_data = TRUE) + 
  labs(title="Predicted Probability of winning based on 3 pointers attempted and points allowed", x="3-point field goals attempted", y="Predicted probability of winning")
```

```{r}
lm_preds <- ggpredict(nba_glm2, terms = c("fg3_pct", "pts_allowed"))
plot(lm_preds, show_data = TRUE) + 
  labs(title="Predicted Probability of winning based on 3 pointers attempted and points allowed", x="3-point field goal percentage", y="Predicted probability of winning")
```

RESIDUAL PLOTS:

```{r}
nba_res <- augment(nba_glm2, type.predict= "response") |>
  dplyr::mutate(.resp.resid = resid(nba_glm2, type= "response"))

# Avg. resids vs. predicted values
arm::binnedplot(nba_glm2$linear.predictors, nba_res$.resp.resid, 
                xlab = "Predicted odds", 
                main = "Binned Residual vs. Predicted Values", 
                col.int = FALSE)

# Individual Binned Residual Plots
arm::binnedplot(nba_res$FG3A, nba_res$.resp.resid, xlab = "FG3A", col.int = NULL)
arm::binnedplot(nba_res$pts_allowed_log, nba_res$.resp.resid, xlab = "pts_allowed_log", col.int = NULL)
arm::binnedplot(nba_res$FTA, nba_res$.resp.resid, xlab = "FTA", col.int = NULL)
arm::binnedplot(nba_res$reb, nba_res$.resp.resid, xlab = "reb", col.int = NULL)
arm::binnedplot(nba_res$SEASON, nba_res$.resp.resid, xlab = "SEASON", col.int = NULL)
arm::binnedplot(nba_res$TO, nba_res$.resp.resid, xlab = "TO", col.int = NULL)
arm::binnedplot(nba_res$fg3_pct, nba_res$.resp.resid, xlab = "fg3_pct", col.int = NULL)
```

```{r}
p_lrm <- lrm(win ~ FG3A  + log(pts_allowed) + FTA  + OREB + DREB + TO, data = final_data) #SEASON IS NOT INCLUDED
p_lrm$stats[c("Dxy", "Gamma", "Tau-a")]
```
